version: '3'

services:
  zookeeper:
    container_name: 'attendance-system-zookeeper'
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181



  kafka:
    container_name: 'attendance-system-kafka'
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  rabbitmq:
    container_name: 'attendance-system-rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis-compose:
    container_name: 'attendance-system-redis-database'
    image: redis:latest
    command: redis-server --requirepass 123 --appendonly yes
    hostname: localhost
    ports:
    - "6378:6379"


  postgres:
    container_name: 'attendance-system-postgres-database'
    image: postgres:latest
    restart: always
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123
    ports:
          - '5434:5432'



  mongodb_container:
    container_name: 'attendance-system-mongo-database'
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: pinhobrunodev
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27017:27017